### ISSUE TITLE
Get the distance and the time of an itinary

### ISSUE THREAD

**Issue by Armays** [perliedman/leaflet-routing-machine#364]
Hello I would like to hide the instructions of an itinary, but the time and distance to be displayed, how can i get the time and the distance ? I read other posts relative to this problem but i didn't manage to make it work. Thanks !

**Comment by perliedman** [comment]
For now, the easiest is probably to add a CSS rule to hide the itinierary instructions:

```css
.leaflet-routing-alt table {
    display: none;
}
```
